version: "3"
services:
  practicabackct:
    image: felipemoralescybertrust/practicabackct:latest
    environment:
      VIRTUAL_HOST: api.localhost
    restart: always
    container_name: practicabackct
    expose:
      - 80
    networks:
      - nginx-proxy

  practicafrontct:
    image: felipemoralescybertrust/practicafrontct:latest
    environment:
      VIRTUAL_HOST: localhost
      REACT_APP_API_URL: api.localhost
    restart: always
    container_name: practicafrontct
    expose:
      - 80
    networks:
      - nginx-proxy

  #servicio proxy entre contenedores
  nginx-proxy:
    #comando para configurar nginx
    command: "sh -c 'echo \"server_tokens off;proxy_connect_timeout 300; proxy_send_timeout 300; proxy_read_timeout 90m; send_timeout 300; client_max_body_size 1024M;\" > /etc/nginx/conf/.d/my_proxy.conf; forego start -r'"
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-poxy

networks:
  nginx-proxy: